[package]
name = "pico-host"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
pico-sdk = { git = "https://github.com/brevis-network/pico", tag = "v1.1.6" }
zkvm_programs = { workspace = true }
dotenv = "0.15.0"
anyhow = "1.0"
bincode = "1.3.3"

#[build-dependencies]
#pico-build = { git = "https://github.com/brevis-network/pico", tag = "v1.1.7" }
#


