use std::time::Instant;

pub fn main() {
    println!("========================================");
    println!("Jolt zkVM Demo - Fibonacci Computation");
    println!("========================================\n");

    // Load fibonacci number from environment
    let fib_n = common::load_fib_n();
    println!("📊 Computing fibonacci({})...\n", fib_n);

    // Build and prove
    println!("1️⃣  Building guest program...");
    let build_start = Instant::now();
    
    // The build_fibonacci function is generated by Jolt's macro system
    // It returns a tuple of (prove_fn, verify_fn)
    let (prove_fibonacci, verify_fibonacci) = jolt_guest::build_fibonacci();
    
    let build_duration = build_start.elapsed();
    println!("   ✓ Build completed in {:.2}s\n", build_duration.as_secs_f64());

    // Generate proof
    println!("2️⃣  Generating proof...");
    let prove_start = Instant::now();
    
    // Call the prove function with the input
    // It returns the output and the proof
    let (output, proof) = prove_fibonacci(fib_n);
    
    let prove_duration = prove_start.elapsed();
    println!("   ✓ Proof generated in {:.2}s", prove_duration.as_secs_f64());
    println!("   ✓ Result: fibonacci({}) = {}\n", fib_n, output);

    // Verify proof
    println!("3️⃣  Verifying proof...");
    let verify_start = Instant::now();
    
    // Verify the proof
    let is_valid = verify_fibonacci(proof);
    
    let verify_duration = verify_start.elapsed();
    
    if is_valid {
        println!("   ✓ Proof verified successfully in {:.2}s\n", verify_duration.as_secs_f64());
        
        println!("========================================");
        println!("📈 Performance Summary");
        println!("========================================");
        println!("Build time:   {:.2}s", build_duration.as_secs_f64());
        println!("Prove time:   {:.2}s", prove_duration.as_secs_f64());
        println!("Verify time:  {:.2}s", verify_duration.as_secs_f64());
        println!("Total time:   {:.2}s", (build_duration + prove_duration + verify_duration).as_secs_f64());
        println!("========================================");
        println!("✅ Jolt zkVM Demo completed successfully!");
        println!("\n💡 Tip: Try running with different FIBONACCI_N values!");
        println!("   Example: FIBONACCI_N=15 cargo run --release");
    } else {
        eprintln!("❌ Proof verification failed!");
        eprintln!("This should not happen with a correctly generated proof.");
        std::process::exit(1);
    }
}
