[package]
name = "sp1-host"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
sp1-sdk = { version = "5.2.2", default-features = false, features = ["profiling", "reserved-capacity"] }


common = { path = "../../common" }
clap = { version = "4.0", features = ["derive", "env"] }

dotenv = "0.15.0"

[build-dependencies]
sp1-build = "5.2.2"
