[package]
name = "sp1-host"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sp1-sdk = { version = "5.0.0", features = ["profiling"] }


common.workspace = true
clap.workspace = true
dotenv.workspace = true

[build-dependencies]
sp1-build = "5.0.0"
