[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "o1vm-host",
]
resolver = "2"

[workspace.dependencies]
programs = { path = "../programs" }

# o1vm dependencies
kimchi = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }
poly-commitment = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }
o1vm = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }
mina-curves = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }
mina-poseidon = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }

# misc
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

