[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "snarkvm-host",
]
resolver = "2"

[workspace.dependencies]
common = { path = "../common" }

# snarkVM dependencies
snarkvm = { version = "0.16", features = ["circuit", "console"] }
snarkvm-circuit = "0.16"
snarkvm-console = "0.16"

# misc
anyhow = "1.0"
colored = "2.1"

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

