[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "common",
    # guest compute logic
    "fib",
    # risc0 zkvm
    "risc0-zkvm/risc0-host",
    "risc0-zkvm/risc0-guest",
    # nexus zkvm
    "nexus-zkvm/nexus-host",
    "nexus-zkvm/nexus-guest",
]
resolver = "2"


[workspace.lints]

[workspace.dependencies]
fib = { path = "fib" }
common = { path = "common" }

#misc
dotenv = "0.15.0"
anyhow = "1.0.98"




# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
