[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    # nexus zkvm, guest and host have to be in the same workspace to compile
    "nexus-host",
    "nexus-guest",
]
resolver = "2"


[workspace.lints]

[workspace.dependencies]
zkvm_programs = { path = "../../programs" }


# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
