[package]
name = "zkm-host"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkm-sdk = { git = "https://github.com/ProjectZKM/Ziren.git", tag = "v1.2.1", default-features = false }

common.workspace = true
clap.workspace = true
dotenv.workspace = true

[build-dependencies]
zkm-build = { git = "https://github.com/ProjectZKM/Ziren.git", tag = "v1.2.1" }
