// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{METHODS_ELF, METHODS_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    // For example:
    let fib_n = common::load_fib_n();
    println!("fib_n = {}", fib_n);
    let env = ExecutorEnv::builder()
        .write(&fib_n)
        .unwrap()
        .build()
        .unwrap();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let opts = ProverOpts::succinct();
    let prove_info = default_prover()
        .prove_with_opts(env, METHODS_ELF, &opts)
        .unwrap();

    println!("Report.paging_cycles {:?}", prove_info.stats.paging_cycles);
    println!(
        "Report.reserved_cycles {:?}",
        prove_info.stats.reserved_cycles
    );
    println!("Report.segments {:?}", prove_info.stats.segments);
    println!("Report.segments {:?}", prove_info.stats.total_cycles);
    println!("Report.segments {:?}", prove_info.stats.user_cycles);

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    // let _output: u32 = receipt.journal.decode().unwrap();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(METHODS_ID).unwrap();
}
