[package]
name = "airbender-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "airbender-host"
path = "src/main.rs"

[dependencies]
zkvm_programs.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
tempfile.workspace = true
thiserror.workspace = true
dotenv.workspace = true
env_logger.workspace = true
log.workspace = true

# ZKsync Airbender SDK
# https://github.com/matter-labs/zksync-airbender
airbender_execution_utils.workspace = true

[build-dependencies]

[features]
default = []

[lints]
workspace = true
