[package]
name = "ceno-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ceno-guest"
path = "src/main.rs"

[dependencies]
# CENO Runtime from Scroll
ceno_rt = { workspace = true }

# Common library for benchmarks
programs = { path = "../../programs", default-features = false }

[features]
cycles = [] # Enable cycle counting
