[package]
name = "powdr-host"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
zkvm_programs = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Powdr SDK
powdr = { version = "0.1.0" }
powdr-number = { version = "0.1.0" }
powdr-backend = { version = "0.1.0" }
powdr-pipeline = { version = "0.1.0" }

[build-dependencies]
