[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "miden-host",
]
resolver = "2"

[workspace.lints]

[workspace.dependencies]
programs = { path = "../programs" }

# Miden VM dependencies
miden-vm = "0.11"
miden-assembly = "0.11"
miden-processor = "0.11"
miden-stdlib = "0.11"

# misc
dotenv = "0.15.0"
anyhow = "1.0.98"

# Always optimize; building and running takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

